const fs=require('fs'),crypto=require('crypto'),{chromium}=require(process.env.STOCK_RADAR_PLAYWRIGHT_MODULE || 'playwright');
const root=process.cwd(),out=root+'/.local/vision-dual-stage-v3',host='http://localhost:8123',base=host+'/quant-review/v3/smoke/';const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),c=await b.newContext({viewport:{width:1440,height:1100}}),p=await c.newPage();
const login=JSON.parse(fs.readFileSync(root+'/data/vision-research/label-studio/local-login.json','utf8').replace(/^\uFEFF/,''));await p.goto(host+'/user/login/');await p.locator('input[name=email]').fill(login.username);await p.locator('input[name=password]').fill(login.password);await p.locator('button[type=submit]').click();await p.waitForURL(u=>!u.pathname.includes('/user/login'));
const errors=[],badResponses=[],requests=[],leftPixels=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)badResponses.push({path:new URL(r.url()).pathname,status:r.status()});});p.on('request',r=>requests.push({url:r.url(),method:r.method()}));
async function csrf(){return (await c.cookies()).find(x=>x.name==='csrftoken').value;}
async function get(url){let r=await c.request.get(url);if(!r.ok())throw Error('GET '+r.status());return r.json();}
async function post(url,body){return c.request.post(url,{data:body,headers:{'X-CSRFToken':await csrf(),'Referer':base}});}
await p.goto(base);await p.waitForFunction(()=>document.querySelector('#left-image')?.naturalWidth>0);if(await p.title()!=='Stock Radar · Dual-stage review')throw Error('page identity');
const tasks=(await get(base+'tasks')).tasks;const existing=await get(base+'export');if(existing.annotations.length)throw Error('Smoke history exists; preserve it and use explicit resume script');
const rawManifest=JSON.parse(fs.readFileSync(out+'/manifest.json','utf8'));const uid=tasks[0].task_id;
const outsider=await b.newContext();let denied=await outsider.request.get(base+'task/'+uid+'/right',{maxRedirects:0});if(denied.status()!==302)throw Error('unauthenticated future fetch');await outsider.close();
let initial=await get(base+'task/'+uid+'/left');
for(const endpoint of ['right']){denied=await c.request.get(base+'task/'+uid+'/'+endpoint);if(denied.status()!==409)throw Error('pre-save right gate');}
denied=await post(base+'task/'+uid+'/reveal',{});if(denied.status()!==409)throw Error('pre-save reveal gate');
denied=await c.request.post(base+'task/'+uid+'/reveal',{data:{}});if(denied.status()!==403)throw Error('CSRF gate '+denied.status()+' '+(await denied.text()).slice(0,100));
denied=await c.request.get(base+'task/'+'f'.repeat(24)+'/left');if(denied.status()!==409)throw Error('foreign task gate');
// A skip is persisted but cannot unlock the original task.
await p.locator('#skip').click();await p.waitForURL(u=>u.searchParams.get('task')!==uid);denied=await post(base+'task/'+uid+'/reveal',{});if(denied.status()!==409)throw Error('skip unlocked future');
const observes=['观察','不观察','不确定'],entries=['当前可买','等回落或进一步确认','不买','不确定'],conf=['高','中','低'];let contaminated=0;
for(let i=0;i<tasks.length;i++){
 const tid=tasks[i].task_id;requests.length=0;await p.goto(base+'?task='+tid);await p.waitForFunction(()=>document.querySelector('#left-image')?.naturalWidth>0);
 const initial=await get(base+'task/'+tid+'/left');if(['Y_future','right_svg','decision_date','security_id','outcome_status','right_hash'].some(k=>k in initial))throw Error('Stage A leaks private/future fields');
 if(requests.some(r=>/\/(right|reveal)$/.test(r.url)))throw Error('future prefetched');if(await p.locator('#right-image').getAttribute('src'))throw Error('future in initial DOM');
 const svg=initial.left_svg;await p.evaluate(()=>window.scrollTo(0,0));const before=await p.locator('#left-image').screenshot();const bounds=await p.locator('#left-image').boundingBox(),view=await p.locator('#left-viewport').boundingBox();if(bounds.height>view.height+1)throw Error('initial chart clipped');
 if(i===0){await p.locator('#observe').selectOption('不观察');await p.locator('#undo').click();if(await p.locator('#observe').inputValue()!=='')throw Error('undo');await p.locator('#recent').click();if(await p.locator('#left-viewport').evaluate(x=>x.scrollLeft)<=0)throw Error('zoom');await p.locator('#zoom-left').fill('1');await p.locator('#zoom-left').dispatchEvent('input');await p.locator('#left-viewport').evaluate(x=>x.scrollLeft=0);await p.screenshot({path:out+'/stage-A.png',fullPage:true});}
 await p.locator('#observe').selectOption(observes[i%3]);await p.locator('#entry').selectOption(entries[i%4]);await p.locator('#confidence').selectOption(conf[i%3]);await p.locator('details').click();await p.locator('#reasons input[value="前期强势"]').check();await p.locator('#reasons input[value="最近涨得过多"]').check();
 await p.locator('#save').click();await p.waitForFunction(()=>!document.querySelector('#reveal').disabled);let saved=await get(base+'task/'+tid+'/left');if(!saved.blind_first)throw Error('not persisted');if(saved.contaminated_retest)contaminated++;
 denied=await c.request.get(base+'task/'+tid+'/right');if(denied.status()!==409)throw Error('save without reveal unlocked right');
 await p.locator('#reveal').click();await p.waitForFunction(()=>document.querySelector('#right-image')?.naturalWidth>0);const right=await get(base+'task/'+tid+'/right');
 await p.evaluate(()=>window.scrollTo(0,0));const after=await p.locator('#left-image').screenshot();if(!before.equals(after)){fs.writeFileSync(out+'/pixel-before.png',before);fs.writeFileSync(out+'/pixel-after.png',after);console.log(JSON.stringify({beforeBounds:bounds,afterBounds:await p.locator('#left-image').boundingBox(),scroll:await p.evaluate(()=>({x:scrollX,y:scrollY}))}));throw Error('left raster changed after reveal');}if((await get(base+'task/'+tid+'/left')).left_svg!==svg)throw Error('left bytes changed');leftPixels.push({before:hash(before),after:hash(after)});
 const privateTask=rawManifest.find(r=>r.task_id===tid);const expected=JSON.parse(fs.readFileSync(out+'/right/'+privateTask.group+'.json','utf8')).Y_future;if(JSON.stringify(expected)!==JSON.stringify(right.Y_future))throw Error('right mismatch actual prepared future');
 await p.locator('#review-reasons input[value="无法归因"]').check();await p.locator('#review-note').fill('Mechanical smoke fixture; not a human judgment.');await p.locator('#save-review').click();await p.waitForFunction(()=>document.querySelector('#review-state').textContent.includes('Saved separate'));
 if(i===0){await p.locator('#observe').selectOption('不观察');await p.locator('#revision-reason').fill('Mechanical post-reveal revision test');await p.locator('#save').click();await p.waitForFunction(()=>document.querySelector('#notice').textContent.includes('post_reveal_revision'));const first=(await get(base+'task/'+tid+'/left')).blind_first;if(JSON.stringify(first)!==JSON.stringify(saved.blind_first))throw Error('blind overwritten');await p.screenshot({path:out+'/stage-B.png',fullPage:true});}
 await p.reload();await p.waitForFunction(()=>document.querySelector('#left-image')?.naturalWidth>0);if(await p.locator('#right-image').getAttribute('src'))throw Error('reload prefetched future');await p.locator('#reveal').click();await p.waitForFunction(()=>document.querySelector('#right-image')?.naturalWidth>0);if(await p.locator('#review-note').inputValue()!=='Mechanical smoke fixture; not a human judgment.')throw Error('review persistence');
 console.log(JSON.stringify({chart:i+1,persisted:true,reveal:true,left_pixels_identical:true}));
}
await p.setViewportSize({width:1280,height:900});await p.reload();await p.waitForFunction(()=>document.querySelector('#left-image')?.naturalWidth>0);if(await p.locator('#left-image').evaluate(x=>x.getBoundingClientRect().right>window.innerWidth))throw Error('desktop clipping');await p.screenshot({path:out+'/desktop-1280.png',fullPage:true});
const smoke=await get(base+'export'),human=await get(host+'/quant-review/v3/human/export');if(human.annotations.length)throw Error('human contamination');if(smoke.annotations.filter(a=>a.phase==='blind').length!==11||smoke.annotations.filter(a=>a.phase==='review').length!==11)throw Error('incomplete smoke');if(contaminated!==1)throw Error('repeat contamination');
fs.writeFileSync(out+'/smoke-export.json',JSON.stringify(smoke,null,2));fs.writeFileSync(out+'/human-empty-export.json',JSON.stringify(human,null,2));
const receipt={status:errors.length||badResponses.length?'FAIL':'PASS',browser:'Chrome / Playwright; Browser plugin not available',browser_version:b.version(),viewports:['1440x1100','1280x900'],distinct_charts:10,tasks:11,initial_network_no_future:true,unauthenticated_right_denied:true,csrf_enforced:true,skip_does_not_reveal:true,persist_save_before_reveal:true,left_svg_unchanged:true,left_raster_identity:leftPixels,review_refresh_resume:true,original_blind_preserved:true,contaminated_retest:contaminated,zoom:true,undo:true,human_annotations:human.annotations.length,errors,unexpected_http:badResponses};fs.writeFileSync(out+'/browser-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));await b.close();if(receipt.status!=='PASS')process.exitCode=1;
})().catch(e=>{console.error(e.message);process.exit(1)});
